### ISSUE TITLE
gpflow error

### ISSUE THREAD

**Issue by marcustutert** [BorgwardtLab/ARDISS#9]
Hi, I've installed the package and have attempted to run the example data but running into an issue:

`
(ardissvenv) (base) [tutert@rescomp2 demo_data]$ ardiss --typed_zscores insomnia_typed_zscores --reference_genotypes genotypes.npy --markers markers.txt
2021-09-07 09:52:28.432013: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-09-07 09:52:28.432051: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/gpfs3/well/mcvean/mtutert/sumstat_imputation_paper/ARDISS/ardissvenv/bin/ardiss", line 5, in <module>
    from ardiss import ardiss_console
  File "/gpfs3/well/mcvean/mtutert/sumstat_imputation_paper/ARDISS/ardissvenv/lib/python3.8/site-packages/ardiss/__init__.py", line 1, in <module>
    from .impute_ard import impute_ard
  File "/gpfs3/well/mcvean/mtutert/sumstat_imputation_paper/ARDISS/ardissvenv/lib/python3.8/site-packages/ardiss/impute_ard.py", line 13, in <module>
    from .ard_model import GPflowARD, load_ard_weights, scale_with_weights
  File "/gpfs3/well/mcvean/mtutert/sumstat_imputation_paper/ARDISS/ardissvenv/lib/python3.8/site-packages/ardiss/ard_model.py", line 14, in <module>
    class GPflowARD(object):
  File "/gpfs3/well/mcvean/mtutert/sumstat_imputation_paper/ARDISS/ardissvenv/lib/python3.8/site-packages/ardiss/ard_model.py", line 20, in GPflowARD
    optimizer=gpflow.train.RMSPropOptimizer(0.1, momentum=0.01),
AttributeError: module 'gpflow' has no attribute 'train'
`

Would someone be able to diagnose what is going wrong here?

**Comment by marcustutert** [comment]
Thanks @mja 
Did end up figuring that out, but thanks for the confirmation!

However, have you managed to get this software to work fully? I've tried to follow the documentation but besides the example data I've not been able to perform any imputation of my own. I keep getting strange numpy errors I'm unable to track down (that seem to suggest there is infinite/missing data etc but doesn't seem like there are based on my reference/sumstat files?

**Comment by mja** [comment]
@marcustutert It did run for me. I'm also looking into [DISTMIX2](https://github.com/Chatzinakos/DISTMIX2).
